version: "3.9"

services:
  rio:
    build:
      context: ./
      dockerfile: Dockerfile
#    image: manabie-com/rio:v1.2.3
#    pull_policy: always
    healthcheck:
      test: curl --fail http://localhost:8896/ping || exit 1
      interval: 15s
      timeout: 30s
      retries: 10
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=rio_services
      - SERVER_PORT=8896
      - FILE_DIR=uploaded_dir
    restart: on-failure
    ports:
      - "8896:8896"
    volumes:
      - shared_data:/app/data
    depends_on:
      - postgres

  # This is for testing purpose since data are not persistent
  # You should mount data accordingly when deploying on your testing environment
  postgres:
    image: postgres
    container_name: rio-postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-rio_services}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  shared_data:
